---
# tasks file for ansible-role-amazon-codedeploy
- block:
  - name: Linux/Unix | Include OS specific variables.
    include_vars: "{{ ansible_os_family }}.yml"

  - name: Install CodeDeploy agent
    include_tasks: "setup-{{ ansible_system }}.yml"

  become: yes
